target-version = "py313"
line-length = 110

[lint]
select = ["E", "F", "I", "B", "UP"]

[lint.isort]
known-first-party = ["custom_components"]
force-sort-within-sections = true
combine-as-imports = true
